In [18]:
import numpy as np
import pandas as pd

In [19]:
crop = pd.read_csv("crop.csv")
crop.head()

,N,P,K,Temp,Humidity,pH,Rainfall,Soil_temp,Soil_moisture,Crop
0,51.3,44.7,20.1,35.4,83.0,5.71,2124.4,26.4,75.6,Rice
1,43.6,30.1,34.5,31.7,56.9,6.22,2032.7,28.5,83.7,Rice
2,28.9,21.3,52.5,29.2,76.5,6.28,2484.7,23.6,84.4,Rice
3,72.8,59.7,10.0,29.9,89.6,6.00,1793.4,29.1,93.8,Rice
4,51.5,56.8,38.7,23.1,96.8,7.41,1848.6,29.5,74.7,Rice

In [20]:
crop.shape

(10000, 10)

In [21]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   N              10000 non-null  float64
 1   P              10000 non-null  float64
 2   K              10000 non-null  float64
 3   Temp           10000 non-null  float64
 4   Humidity       10000 non-null  float64
 5   pH             10000 non-null  float64
 6   Rainfall       10000 non-null  float64
 7   Soil_temp      10000 non-null  float64
 8   Soil_moisture  10000 non-null  float64
 9   Crop           10000 non-null  object
dtypes: float64(9), object(1)
memory usage: 781.4+ KB

In [22]:
crop.isnull().sum()

N                0
P                0
K                0
Temp             0
Humidity         0
pH               0
Rainfall         0
Soil_temp        0
Soil_moisture    0
Crop             0
dtype: int64

In [23]:
crop.duplicated().sum()

np.int64(0)

In [24]:
crop.describe()

,N,P,K,Temp,Humidity,pH,Rainfall,Soil_temp,Soil_moisture
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000
mean,71.151220,35.791030,84.684310,27.355040,61.84096,6.347011,783.110090,25.500310,42.612190
std,63.289245,19.950566,83.942663,4.729167,15.81080,0.532703,642.345549,4.612294,17.316931
min,0.000000,3.000000,10.000000,10.000000,20.00000,4.800000,60.000000,10.000000,5.000000
25%,31.400000,20.700000,37.375000,24.200000,50.00000,6.000000,231.450000,22.500000,30.000000
50%,53.700000,33.600000,57.000000,27.500000,63.50000,6.360000,605.100000,25.700000,41.200000
75%,90.000000,46.900000,99.325000,30.600000,74.40000,6.690000,1059.725000,28.700000,53.600000
max,400.000000,150.000000,500.000000,40.000000,100.00000,8.000000,3000.000000,40.000000,100.000000

In [25]:
print(crop.columns)

Index(['N', 'P', 'K', 'Temp', 'Humidity', 'pH', 'Rainfall', 'Soil_temp',
       'Soil_moisture', 'Crop'],
      dtype='object')

In [26]:
crop['Crop'].value_counts()

Crop
Rice           455
Maize          455
Chickpea       455
Kidneybeans    455
Pigeonpeas     455
Mothbeans      455
Mungbean       455
Blackgram      455
Lentil         455
Pomegranate    455
Banana         455
Mango          455
Grapes         454
Watermelon     454
Muskmelon      454
Apple          454
Orange         454
Papaya         454
Coconut        454
Cotton         454
Jute           454
Coffee         454
Name: count, dtype: int64

In [27]:
crop_dict = {
    'Rice': 1,
    'Maize': 2,
    'Jute': 3,
    'Cotton': 4,
    'Coconut': 5,
    'Papaya': 6,
    'Orange': 7,
    'Apple': 8,
    'Muskmelon': 9,
    'Watermelon': 10,
    'Grapes': 11,
    'Mango': 12,
    'Banana': 13,
    'Pomegranate': 14,
    'Lentil': 15,
    'Blackgram': 16,
    'Mungbean': 17,
    'Mothbeans': 18,
    'Pigeonpeas': 19,
    'Kidneybeans': 20,
    'Chickpea': 21,
    'Coffee': 22
}
crop['crop_num']=  crop['Crop'].map(crop_dict)

In [28]:
crop

,N,P,K,Temp,Humidity,pH,Rainfall,Soil_temp,Soil_moisture,Crop,crop_num
0,51.3,44.7,20.1,35.4,83.0,5.71,2124.4,26.4,75.6,Rice,1
1,43.6,30.1,34.5,31.7,56.9,6.22,2032.7,28.5,83.7,Rice,1
2,28.9,21.3,52.5,29.2,76.5,6.28,2484.7,23.6,84.4,Rice,1
3,72.8,59.7,10.0,29.9,89.6,6.00,1793.4,29.1,93.8,Rice,1
4,51.5,56.8,38.7,23.1,96.8,7.41,1848.6,29.5,74.7,Rice,1
...,...,...,...,...,...,...,...,...,...,...,...
9995,133.6,75.3,74.5,21.0,73.8,6.27,1404.3,19.4,69.6,Coffee,22
9996,95.1,107.4,167.2,21.9,72.9,6.50,1262.3,20.0,46.1,Coffee,22
9997,113.2,80.1,131.4,15.0,68.8,6.50,2113.5,17.6,44.9,Coffee,22
9998,125.5,102.9,103.6,22.1,69.3,6.22,1560.4,22.3,40.4,Coffee,22
9999,98.2,71.8,145.7,20.6,72.3,6.40,1838.6,22.9,45.6,Coffee,22

In [29]:
crop.drop(['Crop'],axis=1,inplace=True)
crop.head()

,N,P,K,Temp,Humidity,pH,Rainfall,Soil_temp,Soil_moisture,crop_num
0,51.3,44.7,20.1,35.4,83.0,5.71,2124.4,26.4,75.6,1
1,43.6,30.1,34.5,31.7,56.9,6.22,2032.7,28.5,83.7,1
2,28.9,21.3,52.5,29.2,76.5,6.28,2484.7,23.6,84.4,1
3,72.8,59.7,10.0,29.9,89.6,6.00,1793.4,29.1,93.8,1
4,51.5,56.8,38.7,23.1,96.8,7.41,1848.6,29.5,74.7,1

In [30]:
X = crop.drop(['crop_num'],axis=1)
y = crop['crop_num']

In [31]:
X

,N,P,K,Temp,Humidity,pH,Rainfall,Soil_temp,Soil_moisture
0,51.3,44.7,20.1,35.4,83.0,5.71,2124.4,26.4,75.6
1,43.6,30.1,34.5,31.7,56.9,6.22,2032.7,28.5,83.7
2,28.9,21.3,52.5,29.2,76.5,6.28,2484.7,23.6,84.4
3,72.8,59.7,10.0,29.9,89.6,6.00,1793.4,29.1,93.8
4,51.5,56.8,38.7,23.1,96.8,7.41,1848.6,29.5,74.7
...,...,...,...,...,...,...,...,...,...
9995,133.6,75.3,74.5,21.0,73.8,6.27,1404.3,19.4,69.6
9996,95.1,107.4,167.2,21.9,72.9,6.50,1262.3,20.0,46.1
9997,113.2,80.1,131.4,15.0,68.8,6.50,2113.5,17.6,44.9
9998,125.5,102.9,103.6,22.1,69.3,6.22,1560.4,22.3,40.4
9999,98.2,71.8,145.7,20.6,72.3,6.40,1838.6,22.9,45.6

In [32]:
y

0        1
1        1
2        1
3        1
4        1
        ..
9995    22
9996    22
9997    22
9998    22
9999    22
Name: crop_num, Length: 10000, dtype: int64

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
y.shape

(10000,)

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [36]:
X_train

,N,P,K,Temp,Humidity,pH,Rainfall,Soil_temp,Soil_moisture
9254,32.9,11.5,44.9,40.0,83.6,5.73,160.0,25.8,58.1
1561,63.1,21.4,41.9,26.4,36.3,5.70,96.9,15.7,10.0
1670,61.2,17.2,32.6,28.4,42.0,5.79,110.4,23.4,21.9
6087,76.4,44.1,103.4,27.8,60.9,6.28,150.6,20.8,25.6
6669,79.9,43.1,99.6,28.3,77.7,7.00,129.5,30.8,34.4
...,...,...,...,...,...,...,...,...,...
5734,32.4,36.0,43.8,27.1,41.8,6.39,646.4,18.8,28.4
5191,46.4,45.9,94.3,24.0,81.8,6.65,800.0,33.5,54.5
5390,95.2,49.9,157.9,30.0,82.0,6.51,997.3,29.3,53.6
860,53.8,41.3,22.1,23.4,75.3,6.11,921.9,30.5,50.3
7270,70.7,39.6,86.3,24.8,54.2,6.15,677.3,18.2,53.7

In [37]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()

X_train = ms.fit_transform(X_train)
X_test = ms.transform(X_test)

In [38]:
X_train

array([[0.08225   , 0.05782313, 0.07122449, ..., 0.03401361, 0.52666667,
        0.55894737],
       [0.15775   , 0.12517007, 0.06510204, ..., 0.01255102, 0.19      ,
        0.05263158],
       [0.153     , 0.09659864, 0.04612245, ..., 0.01714286, 0.44666667,
        0.17789474],
       ...,
       [0.238     , 0.31904762, 0.30183673, ..., 0.31880952, 0.64333333,
        0.51157895],
       [0.1345    , 0.26054422, 0.02469388, ..., 0.29316327, 0.68333333,
        0.47684211],
       [0.17675   , 0.24897959, 0.15571429, ..., 0.20996599, 0.27333333,
        0.51263158]], shape=(8000, 9))

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

# create instances of all models
models = {
    'Logistic Regression': LogisticRegression(),
    'Naive Bayes': GaussianNB(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Bagging': BaggingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'Extra Trees': ExtraTreeClassifier(),
}
for name, model in models.items():
    model.fit(X_train,y_train)
    ypred = model.predict(X_test)
    
    print(f"{name}  with accuracy : {accuracy_score(y_test,ypred)}")
    print("Confusion matrix : ",confusion_matrix(y_test,ypred))
    print("==========================================================")

Logistic Regression  with accuracy : 0.788
Confusion matrix :  [[95  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 72  1  1  0  3  4  2  1  0  0  0  0  6  0  0  0  0  6  0  0  0]
 [ 0  0 76  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0 92  0  0  1  0  0  0  2  0  0  2  0  0  0  0  0  0  0  0]
 [ 2  0  0  0 86  4  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  1]
 [ 0  3  0  1  0 76  6  5  0  0  0  0  0  0  0  0  0  0  1  0  0  8]
 [ 1  7  0  0  2  2 65  2  0  0  1  9  0  0  0  0  0  0  7  0  0  1]
 [ 0  0  0  0  0  0  0 84  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  1 48 36  0  0  0  2  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0 52 45  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0 76  0  0  2  2  0  0  3  7  0  0  0]
 [ 0  0  0  0  0  3  1  0  0  0  0 76  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  0  0  0 93  0  0  0  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  1  0  0  0  1  0  0 84  0  1  1  2  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 62  0  0  1  0  2 11  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0 50 31  6  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  2  0 72 28  6  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  0  0 75  0  0  1  0]
 [ 0  3  0  0  0  1  6  1  1  0 13  0  0  6  0  0  0  0 51  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0 94  4  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0 12  0  0  4  0  7 69  0]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0 79]]
==========================================================
Naive Bayes  with accuracy : 0.8445
Confusion matrix :  [[95  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 81  0  0  0  1  2  0  0  0  0  0  0  3  0  0  0  0  9  0  0  0]
 [ 0  0 76  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  0 93  0  0  1  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 92  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0 98  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  0  0  1  3 78  0  0  0  0  7  0  0  0  0  0  0  5  0  0  0]
 [ 0  0  0  0  0  0  0 84  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  1  0  0  1  0 43 44  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0 57 40  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 85  0  0  1  0  0  0  0  5  0  0  0]
 [ 0  1  0  0  0  0  1  0  0  0  0 77  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 95  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  1  0  0 91  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 66  0  0  0  0  2  8  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0 46 41  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0 62 46  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  5  0  0  0 73  0  0  1  0]
 [ 0  3  0  0  0  0  5  0  0  0  3  0  0  3  0  0  0  0 68  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0 98  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  0  2  0  1 86  0]
 [ 0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 78]]
==========================================================
Support Vector Machine  with accuracy : 0.8325
Confusion matrix :  [[95  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 78  0  1  0  0  4  0  0  0  0  0  0  3  0  0  0  0 10  0  0  0]
 [ 0  0 76  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  0 93  0  0  0  0  0  0  0  0  0  1  0  0  0  0  1  0  0  0]
 [ 0  0  0  0 92  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  0  0 97  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  7  0  0  0  3 77  0  0  0  0  5  0  0  0  0  0  0  5  0  0  0]
 [ 0  0  0  0  0  0  1 84  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 44 44  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0 45 52  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 79  0  0  4  0  0  0  0  7  0  1  0]
 [ 0  1  0  0  0  0  1  0  0  0  0 76  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 95  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0  1  0  0 89  0  1  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 62  0  0  0  0  2 12  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0 62 23  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0 83 23  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  1  0 75  0  0  1  0]
 [ 0  3  0  0  0  0  3  1  0  0 10  0  0  1  0  0  0  0 64  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0 95  4  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  0  0  3  0  2 81  0]
 [ 0  0  0  0  1  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 76]]
==========================================================
K-Nearest Neighbors  with accuracy : 0.8095
Confusion matrix :  [[95  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 70  0  2  0  4  5  1  0  0  0  0  0  5  0  0  0  0  9  0  0  0]
 [ 0  0 76  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  0 89  0  0  0  0  0  0  3  0  0  3  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 90  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3]
 [ 0  0  0  0  0 98  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  5  0  0  0  4 77  0  0  0  1  5  0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  1  0 84  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 47 41  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0 58 37  0  0  0  1  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 84  0  0  2  0  0  0  2  2  0  1  0]
 [ 0  1  0  0  0  1  3  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 95  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  1  0  2  0  0 81  0  2  2  4  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 66  0  0  0  0  3  7  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 46 41  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0 64 42  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  1  0 75  0  0  1  0]
 [ 0  3  0  0  0  1  5  4  1  0 12  0  0  2  0  1  1  0 52  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0 93  5  0]
 [ 0  0  0  0  0  0  0  0  0  1  6  0  0  0  8  0  0  4  0  3 71  0]
 [ 0  0  0  0  1  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 76]]
==========================================================
Decision Tree  with accuracy : 0.7865
Confusion matrix :  [[93  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 66  0  2  0  2  8  5  0  0  0  0  0  1  0  0  1  0 11  0  0  0]
 [ 0  0 76  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0 88  0  0  2  1  0  0  1  0  0  4  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 90  0  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 95  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3]
 [ 0  6  0  2  0  4 71  0  0  0  0  5  0  0  0  0  0  0  7  0  0  2]
 [ 0  1  0  1  0  2  4 75  0  0  0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0 44 46  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 52 44  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  1  0  0  0  0  0  0  0  0 72  0  0  7  0  0  0  0  9  0  2  0]
 [ 0  1  0  1  0  1  4  0  0  0  0 69  0  1  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 95  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  2  0  0  0  5  0  0 78  0  2  0  3  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 57  0  0  0  0  3 16  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  2  0 39 46  0  1  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  2  0  0  0  0 51 55  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  2  0  0  2  0  2  0 72  0  0  1  0]
 [ 0  6  0  0  0  0  9  0  0  0  7  2  0  2  0  1  0  0 55  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  1  0  0  0  0  2  0  0  0  0 96  2  0]
 [ 0  0  0  0  0  0  0  0  0  1  2  0  0  0 13  1  0  5  0  1 70  0]
 [ 2  0  0  0  1  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 73]]
==========================================================
Random Forest  with accuracy : 0.8425
Confusion matrix :  [[94  1  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 86  0  0  0  1  2  0  0  0  0  0  0  2  0  0  0  0  5  0  0  0]
 [ 0  0 76  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  0 94  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 94  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 99  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  1 81  2  0  0  0  4  0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  1 82  0  0  0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0 43 45  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0 59 38  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 83  0  0  4  0  0  0  0  4  0  0  0]
 [ 0  1  0  0  0  0  2  0  0  0  0 76  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 95  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0 91  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 64  0  0  0  0  1 11  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  2  0 51 35  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 72 37  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0  3  0  0  0 73  0  0  2  0]
 [ 0  5  0  0  0  0  3  0  0  0  4  0  0  2  0  0  0  0 68  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0 99  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  6  0  0  2  0  0 85  0]
 [ 0  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 76]]
==========================================================
Bagging  with accuracy : 0.8245
Confusion matrix :  [[94  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 78  0  1  0  1  3  1  0  0  1  1  0  2  0  0  0  0  8  0  0  0]
 [ 0  0 76  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  0 92  0  0  1  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 92  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 96  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  7  0  0  0  5 76  2  0  0  0  3  0  1  0  0  0  0  3  0  0  0]
 [ 0  1  0  0  0  1  5 77  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0 50 38  0  0  0  0  1  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0 60 36  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0 81  0  0  4  0  0  0  0  6  0  0  0]
 [ 0  2  0  0  0  0  5  0  0  0  0 72  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 95  0  0  0  0  0  0  0  0  0]
 [ 0  3  0  1  0  0  1  0  0  0  4  0  0 83  0  0  0  1  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 64  0  0  0  0  1 11  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  2  0 55 31  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 68 41  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  1  0  0  3  0  0  0 74  0  0  1  0]
 [ 0  8  0  0  0  0  5  0  0  0  5  0  0  1  0  0  0  0 63  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0 97  3  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  6  0  0  4  0  0 83  0]
 [ 1  0  0  0  1  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 74]]
==========================================================
AdaBoost  with accuracy : 0.2595
Confusion matrix :  [[ 92   0   0   0   0   0   0   0   0   0   0   2   0   0   0   0   0   0
    0   0   0   2]
 [  0   0   0  18   0   0   0   0   0   0   0  78   0   0   0   0   0   0
    0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0  76   0]
 [  0   0   0  76   0   0   0   0   0   0   0  22   0   0   0   0   0   0
    0   0   0   0]
 [ 94   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0]
 [  0   0   0  13   0   0   0   0   0   0   0  66   0   0   0   0   0   0
    0   0   0  21]
 [  0   0   0   0   0   0   0   0   0   0   0  91   0   0   0   0   0   0
    0   0   0   6]
 [  0   0   0   0   0   0   0   0   0   0   0  85   0   0   0   0   0   0
    0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0
    0  32  57   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0  24  73   0]
 [  0   0   0   0   0   0   0   0   0   0   0  91   0   0   0   0   0   0
    0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  80   0   0   0   0   0   0
    0   0   0   0]
 [  3   0   0   0   0   0   0   0   0   0   0   0  92   0   0   0   0   0
    0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  90   0   0   0   0   5   0
    0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   2   0
    0   6  68   0]
 [  0   0   0   0   0   0   0   0   0   0   0  84   0   0   0   0   4   0
    0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0 106   0   0   0   0   3   0
    0   0   0   0]
 [  0   0   0   0   0   0   0   0   2   0   0  14   0   0   0   0  35   0
    0   0  29   0]
 [  0   0   0   0   0   0   0   0   0   0   0  82   0   0   0   0   0   0
    0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0  94   8   0]
 [  0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   4   0
    0   9  79   0]
 [ 71   0   0   3   0   0   0   0   0   0   0   3   0   0   0   0   0   0
    0   0   0   3]]
==========================================================
Gradient Boosting  with accuracy : 0.8525
Confusion matrix :  [[ 95   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0]
 [  0  87   0   0   0   1   1   0   0   0   0   0   0   3   0   0   0   0
    4   0   0   0]
 [  0   0  76   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0]
 [  0   3   0  89   0   0   3   0   0   0   1   0   0   1   0   0   0   1
    0   0   0   0]
 [  0   0   0   0  94   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0]
 [  0   0   0   0   0  98   2   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0]
 [  0   5   0   0   0   0  87   0   0   0   0   2   0   0   0   0   0   0
    3   0   0   0]
 [  0   2   0   0   0   0   0  82   0   0   0   0   0   0   0   0   0   0
    1   0   0   0]
 [  0   0   0   0   0   0   0   1  42  44   0   0   0   1   0   0   0   0
    0   0   2   0]
 [  0   0   0   0   0   0   0   0  46  51   0   0   0   0   0   0   0   0
    0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  81   0   0   5   0   0   0   0
    5   0   0   0]
 [  0   1   0   0   0   0   2   0   0   0   0  75   0   0   0   0   0   0
    2   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0  95   0   0   0   0   0
    0   0   0   0]
 [  0   2   0   0   0   0   0   0   0   0   1   0   0  90   0   1   0   0
    1   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0  64   0   0   1
    0   2   9   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  48  40   0
    0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  65  44   0
    0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0   3   0   0   2   0   1   0  73
    0   0   0   0]
 [  0   2   0   0   0   0   3   0   0   0   3   0   0   2   0   0   0   0
   72   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0
    0 100   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   5   0   0   2
    0   0  86   0]
 [  0   0   0   0   1   3   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0  76]]
==========================================================
Extra Trees  with accuracy : 0.732
Confusion matrix :  [[93  1  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0 63  1  2  0  1  8  3  0  0  0  0  0  7  0  0  0  0 11  0  0  0]
 [ 0  0 76  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0 75  0  0  2  0  1  4  0  0  0  7  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 78  2  0  0  0  0  0  6  2  0  0  0  0  0  0  0  0  6]
 [ 1  0  0  0  1 86  5  0  1  0  0  2  0  0  0  0  0  0  0  0  0  4]
 [ 5  9  0  1  3  2 60  3  0  1  0 10  0  0  0  0  0  0  3  0  0  0]
 [ 0  2  0  0  0  2  4 74  0  0  2  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0 43 41  0  1  0  1  1  0  0  0  0  1  2  0]
 [ 0  0  0  0  0  0  0  0 50 44  0  1  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  2  0  0 63  0  0  6  0  0  3  1 12  0  4  0]
 [ 0  1  0  1  1  0  8  1  0  0  0 64  0  0  0  0  0  0  2  0  0  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 95  0  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  1  0  0  0  3  0  0 71  2  2  2  2  7  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  0  0  0 58  0  0  0  0  1 16  0]
 [ 0  0  0  1  0  0  0  0  0  0  1  0  0  0  0 41 43  2  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  2  0  0  1  0 51 48  5  1  0  0  0]
 [ 0  1  0  1  0  0  0  0  0  0  2  0  0  3  2  1  3 64  0  0  3  0]
 [ 1 13  0  0  0  1  8  1  0  0  5  0  0  3  0  1  1  0 48  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  0  0  0  5  0  0  0  0 93  3  0]
 [ 0  0  0  0  0  0  0  0  0  2  1  0  0  0 18  1  0  7  0  2 62  0]
 [ 3  0  0  0  2  7  1  0  0  0  0  1  1  0  0  0  0  0  0  0  0 65]]
==========================================================

In [40]:
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
ypred = rfc.predict(X_test)
accuracy_score(y_test,ypred)

0.847

In [41]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)
ypred = gnb.predict(X_test)
accuracy_score(y_test,ypred)

0.8445

In [42]:
def recommendation(N,P,k,temperature,humidity,ph,rainfal,Soil_temp,Soil_moisture):
    features = np.array([[N,P,k,temperature,humidity,ph,rainfal,Soil_temp,Soil_moisture]])
    transformed_features = ms.fit_transform(features)
    prediction = rfc.predict(transformed_features)
    print(prediction)
    return prediction[0]

In [43]:
N = 40
P = 50
k = 50
temperature = 40.0
humidity = 20
ph = 100
rainfall = 100
Soil_temp=25
Soil_moisture=33

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall,Soil_temp,Soil_moisture)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[20]
Kidneybeans is a best crop to be cultivated

In [44]:
import inspect
print(inspect.signature(recommendation))

(N, P, k, temperature, humidity, ph, rainfal, Soil_temp, Soil_moisture)

In [45]:
# new inputs 2
N = 10
P = 10
k = 10
temperature = 15.0
humidity = 80.0
ph = 4.5
rainfall = 10.0
Soil_temp=25
Soil_moisture=33

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall,Soil_temp,Soil_moisture)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[20]
Kidneybeans is a best crop to be cultivated

In [46]:
import pickle
pickle.dump(rfc,open('model.pkl','wb'))
pickle.dump(ms,open('minmaxscaler.pkl','wb'))

In [47]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

pickle.dump(scaler, open('standscaler.pkl', 'wb'))